#!/bin/bash
PS3="Хотите ли Вы установить python? "
echo
select option in "Да" "Нет"
do
case $option in
Да) echo  “Вы выбрали установить python” 
break ;;
Нет) echo  “Уходи дверь закрой” 
break ;;
esac
done
exit 0
